name: CI

on: [push, pull_request]

jobs:
  test-go-native:
    name: Test (Go-native)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Run tests (Go-native, with coverage)
        run: make test

      - name: Upload coverage artifact (Go-native)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-go-native
          path: coverage.out

  test-python:
    name: Test (Python reference)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download uv binary
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}

      - name: Install Python dependencies (uv)
        run: make install

      - name: Check backend presence and executability
        run: |
          test -x pyver_backend.py || (echo "pyver_backend.py missing or not executable" && exit 1)

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Run tests (Python reference)
        run: make test-python

  test-backend:
    name: Test (Python backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download uv binary
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Python dependencies (uv)
        run: make install

      - name: Check backend presence and executability
        run: |
          test -x pyver_backend.py || (echo "pyver_backend.py missing or not executable" && exit 1)

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run tests (backend, with coverage)
        run: make test-python
